import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False, slow_mo=500)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://sen211-e-learning-project.onrender.com/")
    page.get_by_text("COS 111 8 Courses 3 Quizzes").click()
    page.goto("https://sen211-e-learning-project.onrender.com/auth/login.html")
    page.get_by_placeholder("Email").click()
    page.get_by_placeholder("Email").type("charlesocean2024@gmail.com",delay=100)
    page.get_by_placeholder("Password").click()
    page.get_by_placeholder("Password").type("Testing123",delay=100)
    # page.get_by_placeholder("Password").press("Enter")
    # page.get_by_placeholder("Password").press("Enter")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_text("COS 111").click()
    page.get_by_role("button", name="Module Quiz").click()
    page.get_by_text("Start").click()
    page.get_by_role("link", name="Submit").click()
    page.get_by_text("Review result").click()
    page.get_by_text("Finish Review").click()
    page.goto("https://sen211-e-learning-project.onrender.com/index.html")
    page.get_by_text("COS 121").click()
    page.get_by_role("button", name="Module Quiz").get_by_role("link").click()
    page.goto("https://sen211-e-learning-project.onrender.com/modules/COS121/Quiz/module2.quiz.html")
    page.get_by_text("Start").click()
    page.get_by_role("link", name="Submit").click()
    page.get_by_role("link", name="Finish Review").click()
    page.goto("https://sen211-e-learning-project.onrender.com/index.html")
    page.get_by_text("MTH 111/").click()
    page.goto("https://sen211-e-learning-project.onrender.com/index.html")
    page.get_by_text("PHY 111/").click()
    page.get_by_text("PHY111 Quiz 2").click()
    page.goto("https://sen211-e-learning-project.onrender.com/modules/PHY111_117/materials/module4.quiz.html?file=module4.quiz.2.json")
    page.get_by_text("Start").click()
    page.get_by_text("Submit").click()
    page.get_by_text("Review result").click()
    page.get_by_text("Finish Review").click()
    page.goto("https://sen211-e-learning-project.onrender.com/index.html")
    page.get_by_text("UNIUYO-CSC 111").click()
    page.get_by_role("button", name="Module Quiz").click()
    page.get_by_text("Start").click()
    page.get_by_role("link", name="Submit").click()
    page.get_by_role("link", name="Finish Review").click()
    page.goto("https://sen211-e-learning-project.onrender.com/index.html")
    page.get_by_text("UNIUYO-CSC 112").click()
    page.get_by_role("button", name="Module Quiz").click()
    page.get_by_text("Start", exact=True).click()
    page.get_by_text("Submit").click()
    page.goto("https://sen211-e-learning-project.onrender.com/index.html")
    page.get_by_text("UNIUYO-CSC 121").click()
    page.get_by_text("UNIUYO-CSC 122").click()
    page.get_by_text("UUY-CSC 122 Quiz 2").click()
    page.get_by_text("Start").click()
    page.get_by_text("Submit").click()
    page.get_by_text("Review result").click()
    page.get_by_text("Finish Review").click()
    page.goto("https://sen211-e-learning-project.onrender.com/index.html")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
